logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
#    org.springframework.boot.autoconfigure: DEBUG

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/todo
    username: root
    password: 123456

  jpa:
    hibernate:
      ddl-auto: none

jwt:
  private.key: classpath:app.key
  public.key: classpath:app.pub
  token:
    expiration: 30